[package]
name = "rssb"
version = "0.0.1"
authors = ["ah-OOG-ah"]
edition = "2021"
license = "LGPL-3.0-or-later"
publish = false

[dependencies]
rss = { path = "rss" }

[build-dependencies]
spirv-builder = "0.9.0"
