[package]
name = "rust_shader"
version = "0.0.1"
authors = ["ah-OOG-ah"]
edition = "2024"
license = "LGPL-3.0-or-later"
build = "build.rs"
publish = false

[lib]
crate-type = ["dylib"]

[build-dependencies]
spirv-builder = "0.9"
