[package]
name = "rss"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
crate-type = ["dylib"]

[dependencies]
spirv-std = "0.9.0"
